### ISSUE TITLE
Intraday_all does not Work

### ISSUE THREAD

**Issue by JoelhoAC** [simonbromberg/googlefitbit#25]
By downloading the data, I do get the Error : "Method "getmaxRows" from zero can not be run.
Can anyone help on this?   

 var doc = SpreadsheetApp.getActiveSpreadsheet();
    var sheet = doc.getSheetByName(mySheetName);
    var lastrow = sheet.getMaxRows();
    sheet.clear();
    if (lastrow > 3) { sheet.deleteRows(2, lastrow -2); }
    sheet.setFrozenRows(1);

Thank you

**Comment by dsoiM** [comment]
Does a sheet exist with the correct name defined in mySheetName?
Try adding some rows to the sheet as well

**Comment by JoelhoAC** [comment]
Yes. :) I completely followed the instructions! And the sheet does have the correct name  ...

**Comment by stuzog** [comment]
I get the same error labelled "TypeError: Cannot call method "getMaxRows" of null."

**Comment by simonbromberg** [comment]
I did not write this version of the script, and it should be updated so it doesn't force the name of the sheet that way (and instead using the active sheet like the other scripts).

But I set up a new sheet with the script as is just now and re-confirmed that it works fine if set up correctly.

The error you're seeing is because it cannot find the "Sheet1" it is expecting to find. I changed the name of the sheet and got the same error.

If you still don't know what to do, you can try taking a look at the other scripts and changing it so it uses the active sheet instead of looking for a sheet by a specific name.

**Comment by simonbromberg** [comment]
`getActiveSheet()` ought to do it

**Comment by stuzog** [comment]
Thanks for the hint, @simonbromberg I fixed it by:
1. changing line 16 to the name i had given to the sheet;
2. line 118 firstDate to the first date in my Fitbit data collection; and
3. line 249 to var sheet = doc.getActiveSheet();
